/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Donation = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Opt(IDL.Text),
  'message' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'donor' : IDL.Principal,
});

export const idlService = IDL.Service({
  'getDonation' : IDL.Func([IDL.Nat], [Donation], ['query']),
  'getDonationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getDonationsByAmount' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getRecentDonations' : IDL.Func([IDL.Nat], [IDL.Vec(Donation)], ['query']),
  'getTotalAmount' : IDL.Func([], [IDL.Nat], ['query']),
  'searchDonationsByAmount' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Donation)],
      ['query'],
    ),
  'searchDonationsByDonor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Donation)],
      ['query'],
    ),
  'submitDonation' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Donation = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Opt(IDL.Text),
    'message' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'donor' : IDL.Principal,
  });
  
  return IDL.Service({
    'getDonation' : IDL.Func([IDL.Nat], [Donation], ['query']),
    'getDonationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getDonationsByAmount' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getRecentDonations' : IDL.Func([IDL.Nat], [IDL.Vec(Donation)], ['query']),
    'getTotalAmount' : IDL.Func([], [IDL.Nat], ['query']),
    'searchDonationsByAmount' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Donation)],
        ['query'],
      ),
    'searchDonationsByDonor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Donation)],
        ['query'],
      ),
    'submitDonation' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };