/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Donation {
  'id' : bigint,
  'name' : [] | [string],
  'message' : [] | [string],
  'timestamp' : bigint,
  'amount' : bigint,
  'donor' : Principal,
}
export interface _SERVICE {
  'getDonation' : ActorMethod<[bigint], Donation>,
  'getDonationCount' : ActorMethod<[], bigint>,
  'getDonationsByAmount' : ActorMethod<[], Array<Donation>>,
  'getRecentDonations' : ActorMethod<[bigint], Array<Donation>>,
  'getTotalAmount' : ActorMethod<[], bigint>,
  'searchDonationsByAmount' : ActorMethod<[bigint], Array<Donation>>,
  'searchDonationsByDonor' : ActorMethod<[Principal], Array<Donation>>,
  'submitDonation' : ActorMethod<
    [bigint, [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];